version: "2"

run:
  timeout: 5m
  issues-exit-code: 2
  tests: false

linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - importas
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
            - github.com/ealebed/token-injector/token-injector
            - github.com/ealebed/token-injector/token-injector/internal/gcp
            - cloud.google.com/go/compute/metadata
            - github.com/dgrijalva/jwt-go
            - github.com/pkg/errors
            - github.com/urfave/cli/v2
            - golang.org/x/oauth2
            - google.golang.org/api
            - google.golang.org/api/iamcredentials/v1
    govet:
      enable:
        - nilness
        - shadow
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 3
    misspell:
      locale: US
    lll:
      line-length: 160
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - rangeValCopy
        - unnamedResult
        - whyNoLint
        - wrapperFunc
    funlen:
      lines: -1
      statements: 50

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/ealebed/token-injector

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
